### PR TITLE
Patch #26

### LINKED ISSUE #26: [Bug] Laplace Mechanism File Writing Error
**Describe the bug**
Writes to a file with the privatized data like:
```csv
[a, b, c, d]
```
instead of:
```csv
a, b, c, d
```
**To Reproduce**
Try to use some example data:
```python
from DiffPriv import diff as private

def avg(arr):

    sum = 0
    for i in arr: sum += i
    return sum / len(arr)

file = open('data.csv', 'r')
private.lapmech(file, 'output.csv', 1.0, avg)
```
With `data.csv`:
```csv
2,2,2,2,2,1,3,4
```
and check the output at `output.csv`, and you get it as if it were an array and not in `.csv` format.

**Expected behavior**
It should output something like:
```csv
a, b, c, d
```
and not:
```csv
[a, b, c, d]
```

**Anaconda**
- **Anaconda Version** - conda 4.10.3
- **Operating System** - Windows
- **DiffPriv Version** - 1.0.2, latest

**Additional context**
This is for the `laplech` mechanism, but hasn't been checked for the exponential mechanism, so it is possible the issue is there too.

Work will on branch `patch-#26` and will be merged into `main`, but the commit (be it one commit or a squash commit) will be checked out to `maintenance/v1.0.x`, and the target for the patch release will also be on `maintenance/v1.0.x`.

### PR DESCRIPTION
**Pull request by Quantalabs**
# Patch #26
___

## New Feature
None.

## Known Issues
#26 - The Laplace and Exponential mechanism both write to files as arrays, instead of in a `.csv` format. See the issue for details.

## Code Breakdown
`DiffPriv/diff.py`:
  - Fix Laplace Bug (#26)
  - Fix Exponential bug (#26)

## Additional Notes
**Closes #26**

### CODE REVIEW

**Review by quantum9Innovation — CHANGES_REQUESTED** [review]
This is not the right way of doing it; by converting each element of the array one-by-one to a string, further mathematical operations cannot be performed *and* it compromises code readability. It is much easier to convert the entire list at the last line to a list of strings with the simple command:
```python
line = " ".join(str(x) for x in line)
```

**Comment by quantum9Innovation** [comment]
@Quantalabs are you sure you want auto-merge or should we disable it?

**Comment by Quantalabs** [comment]
Auto-merge is fine.

**Comment by Quantalabs** [comment]
> 
> 
> This is not the right way of doing it; by converting each element of the array one-by-one to a string, further mathematical operations cannot be performed _and_ it compromises code readability. It is much easier to convert the entire list at the last line to a list of strings with the simple command:
> 
> ```python
> line = " ".join(str(x) for x in line)
> ```

Fixed in 2661757

**Review by quantum9Innovation — APPROVED** [review]
Looks good now; ready to merge after tests pass

**Comment by Quantalabs** [comment]
:shipit: `v1.0.3` will get published after commits are checked out onto `maintenance/v1.0.x` and version info is updated.

**Pull request merged**
